### ISSUE TITLE
KeyError: 'cocobu_box\\1000'

### ISSUE THREAD

**Issue by violet2274** [yahoo/object_relation_transformer#19]
$ python scripts/prepro_bbox_relative_coords.py --input_json data/dataset_coco.json --input_box_dir data/cocobu_box --output_dir data/cocobu_box_relative --image_root image
Reading coco dataset info
Output dir: data/cocobu_box_relative
processed 0 images (of 123287)
Traceback (most recent call last):
  File "scripts/prepro_bbox_relative_coords.py", line 102, in <module>
    get_bbox_relative_coords(params)
  File "scripts/prepro_bbox_relative_coords.py", line 80, in get_bbox_relative_coords
    img_path=coco_ids_to_paths[filenumber]
KeyError: 'cocobu_box\\1000'
How to solve this problem?

**Comment by qq123aa456** [comment]
have you solved this?the same error
